-- Seed: 197 сервисов из docs/seed-services.csv. Идемпотентно: повторный запуск
-- обновляет существующие записи по sku, не создаёт дубликатов. category_id
-- резолвится через category.sku (см. 0009_seed_categories.sql).
INSERT INTO "service" ("sku", "name", "icon", "category_id", "cancel_url", "pricing_url")
SELECT v.sku, v.name, v.icon, c.id, v.cancel_url, v.pricing_url
FROM (VALUES
    ('KN84JXN6', 'Netflix', '/icons/netflix.svg', 'N9095NFS', 'https://www.netflix.com/cancelplan', 'https://www.netflix.com/signup/planform'),
    ('N50MK3M6', 'Disney+', '/icons/disneyplus.svg', 'N9095NFS', 'https://www.disneyplus.com/', 'https://www.disneyplus.com/welcome'),
    ('RFCE7JKF', 'Max', '/icons/max.svg', 'N9095NFS', 'https://auth.max.com/', 'https://auth.max.com/signup'),
    ('G6EHWBFM', 'Hulu', '/icons/hulu.svg', 'N9095NFS', 'https://www.hulu.com/', 'https://www.hulu.com/welcome'),
    ('JPCFEHE8', 'Apple TV+', '/icons/appletv.svg', 'N9095NFS', 'https://apps.apple.com/account/subscriptions', 'https://www.apple.com/apple-tv-plus/'),
    ('7K8NFBGX', 'Amazon Prime Video', '/icons/primevideo.svg', 'N9095NFS', 'https://www.amazon.com/', 'https://www.amazon.com/amazonprime'),
    ('4Y8W5P5Z', 'Paramount+', '/icons/paramountplus.svg', 'N9095NFS', 'https://www.paramountplus.com/', 'https://www.paramountplus.com/account/signup/'),
    ('AM89EC21', 'Peacock', '/icons/peacock.svg', 'N9095NFS', 'https://www.peacocktv.com/', 'https://www.peacocktv.com/plans'),
    ('45XH81XZ', 'Crunchyroll', '/icons/crunchyroll.svg', 'N9095NFS', 'https://www.crunchyroll.com/', 'https://www.crunchyroll.com/welcome'),
    ('CNER5P3E', 'Mubi', '/icons/mubi.svg', 'N9095NFS', 'https://mubi.com/', 'https://mubi.com/'),
    ('BRYRDACV', 'Plex Pass', '/icons/plex.svg', 'N9095NFS', 'https://www.plex.tv/', 'https://www.plex.tv/plex-pass/'),
    ('1JS75TTJ', 'Discovery+', '/icons/discoveryplus.svg', 'N9095NFS', 'https://www.discoveryplus.com/', 'https://www.discoveryplus.com/'),
    ('VT00AZ2W', 'ESPN+', '/icons/espnplus.svg', 'N9095NFS', 'https://plus.espn.com/', 'https://plus.espn.com/'),
    ('GCXA6VFA', 'Кинопоиск', '/icons/kinopoisk.svg', 'N9095NFS', 'https://plus.yandex.ru/myplus', 'https://hd.kinopoisk.ru/'),
    ('24Q0WY4T', 'Okko', '/icons/okko.svg', 'N9095NFS', 'https://okko.tv/', 'https://okko.tv/'),
    ('MDQYABYK', 'Иви', '/icons/ivi.svg', 'N9095NFS', 'https://www.ivi.ru/', 'https://www.ivi.ru/'),
    ('JY7QKHYN', 'Wink', '/icons/wink.svg', 'N9095NFS', 'https://wink.ru/', 'https://wink.ru/'),
    ('W29G07JH', 'START', '/icons/startru.svg', 'N9095NFS', 'https://start.ru/', 'https://start.ru/'),
    ('8MS9MDGY', 'Premier', '/icons/premier.svg', 'N9095NFS', 'https://premier.one/', 'https://premier.one/'),
    ('A9N07SH3', 'MORE.TV', '/icons/moretv.svg', 'N9095NFS', 'https://more.tv/', 'https://more.tv/'),
    ('WH6HQH3S', 'Билайн ТВ', '/icons/beelinetv.svg', 'N9095NFS', 'https://moretv.tv/', 'https://moretv.tv/'),
    ('4V4415QF', 'Megafon TV', '/icons/megafontv.svg', 'N9095NFS', 'https://megafontv.ru/', 'https://megafontv.ru/'),
    ('K692Y4MN', 'Spotify', '/icons/spotify.svg', 'BPBXYE18', 'https://www.spotify.com/account/subscription/cancel/', 'https://www.spotify.com/premium/'),
    ('TQV1SF4W', 'Apple Music', '/icons/applemusic.svg', 'BPBXYE18', 'https://apps.apple.com/account/subscriptions', 'https://www.apple.com/apple-music/'),
    ('DRTHGR2T', 'YouTube Music', '/icons/youtubemusic.svg', 'BPBXYE18', 'https://myaccount.google.com/subscriptions', 'https://music.youtube.com/'),
    ('HJN5RA13', 'Tidal', '/icons/tidal.svg', 'BPBXYE18', 'https://tidal.com/', 'https://tidal.com/pricing'),
    ('PG0MTW1S', 'Deezer', '/icons/deezer.svg', 'BPBXYE18', 'https://www.deezer.com/', 'https://www.deezer.com/offers'),
    ('H3WSVJAY', 'SoundCloud Go+', '/icons/soundcloud.svg', 'BPBXYE18', 'https://soundcloud.com/', 'https://soundcloud.com/'),
    ('JAVBFYKG', 'Amazon Music Unlimited', '/icons/amazonmusic.svg', 'BPBXYE18', 'https://www.amazon.com/', 'https://www.amazon.com/music/unlimited'),
    ('E602VGHE', 'Pandora Premium', '/icons/pandora.svg', 'BPBXYE18', 'https://www.pandora.com/', 'https://www.pandora.com/upgrade'),
    ('DAER3EAE', 'iHeartRadio Plus', '/icons/iheartradio.svg', 'BPBXYE18', 'https://www.iheart.com/', 'https://www.iheart.com/'),
    ('0FB4E347', 'Anghami Plus', '/icons/anghami.svg', 'BPBXYE18', 'https://www.anghami.com/', 'https://www.anghami.com/plus'),
    ('0W7NNRZ6', 'JioSaavn Pro', '/icons/jiosaavn.svg', 'BPBXYE18', 'https://www.jiosaavn.com/', 'https://www.jiosaavn.com/pro'),
    ('BZQYNMJQ', 'ВК Музыка', '/icons/vkmusic.svg', 'BPBXYE18', 'https://vk.com/', 'https://vk.com/music'),
    ('JS7JDECH', 'МТС Music', '/icons/mtsmusic.svg', 'BPBXYE18', 'https://music.mts.ru/', 'https://music.mts.ru/'),
    ('9VQZZ5QR', 'Napster', '/icons/napster.svg', 'BPBXYE18', 'https://www.napster.com/', 'https://www.napster.com/'),
    ('SW6SZJN1', 'Audiomack Premium', '/icons/audiomack.svg', 'BPBXYE18', 'https://audiomack.com/', 'https://audiomack.com/premium'),
    ('15N1A5EZ', 'Coursera Plus', '/icons/coursera.svg', 'F10MPC5T', 'https://www.coursera.org/', 'https://www.coursera.org/courseraplus'),
    ('SHFJ6KCZ', 'edX Verified', '/icons/edx.svg', 'F10MPC5T', 'https://www.edx.org/', 'https://www.edx.org/'),
    ('RFCR46MG', 'Udemy Personal Plan', '/icons/udemy.svg', 'F10MPC5T', 'https://www.udemy.com/', 'https://www.udemy.com/personal-plan/'),
    ('71XVTTS3', 'Skillshare', '/icons/skillshare.svg', 'F10MPC5T', 'https://www.skillshare.com/', 'https://www.skillshare.com/en/membership'),
    ('0A44HH2X', 'MasterClass', '/icons/masterclass.svg', 'F10MPC5T', 'https://www.masterclass.com/', 'https://www.masterclass.com/pricing'),
    ('KZ6B6CQE', 'Pluralsight', '/icons/pluralsight.svg', 'F10MPC5T', 'https://www.pluralsight.com/', 'https://www.pluralsight.com/pricing'),
    ('D105ZAHD', 'LinkedIn Learning', '/icons/linkedin.svg', 'F10MPC5T', 'https://www.linkedin.com/', 'https://www.linkedin.com/learning/subscription/products'),
    ('HGBABBVH', 'Brilliant Premium', '/icons/brilliant.svg', 'F10MPC5T', 'https://brilliant.org/', 'https://brilliant.org/premium/'),
    ('CW5RYY62', 'DataCamp', '/icons/datacamp.svg', 'F10MPC5T', 'https://www.datacamp.com/', 'https://www.datacamp.com/pricing'),
    ('7BP56XXJ', 'Codecademy Pro', '/icons/codecademy.svg', 'F10MPC5T', 'https://www.codecademy.com/', 'https://www.codecademy.com/pricing'),
    ('6T20V383', 'Treehouse', '/icons/treehouse.svg', 'F10MPC5T', 'https://teamtreehouse.com/', 'https://teamtreehouse.com/'),
    ('W6C3XGCX', 'Udacity', '/icons/udacity.svg', 'F10MPC5T', 'https://www.udacity.com/', 'https://www.udacity.com/pricing'),
    ('8E930NA4', 'egghead.io', '/icons/egghead.svg', 'F10MPC5T', 'https://egghead.io/', 'https://egghead.io/pricing'),
    ('BDFHQ3ZD', 'Babbel', '/icons/babbel.svg', 'F10MPC5T', 'https://www.babbel.com/', 'https://www.babbel.com/prices'),
    ('TEDT39MN', 'Busuu Premium', '/icons/busuu.svg', 'F10MPC5T', 'https://www.busuu.com/', 'https://www.busuu.com/products/en'),
    ('NZCZMAYR', 'Rosetta Stone', '/icons/rosettastone.svg', 'F10MPC5T', 'https://www.rosettastone.com/', 'https://www.rosettastone.com/'),
    ('NJ762F9G', 'Pimsleur', '/icons/pimsleur.svg', 'F10MPC5T', 'https://www.pimsleur.com/', 'https://www.pimsleur.com/'),
    ('SXZPQ6DG', 'Skillbox', '/icons/skillbox.svg', 'F10MPC5T', 'https://skillbox.ru/', 'https://skillbox.ru/'),
    ('DATTC8CJ', 'GeekBrains', '/icons/geekbrains.svg', 'F10MPC5T', 'https://gb.ru/', 'https://gb.ru/'),
    ('8CXD49FK', 'Нетология', '/icons/netology.svg', 'F10MPC5T', 'https://netology.ru/', 'https://netology.ru/'),
    ('A4GFKBB0', 'Яндекс Практикум', '/icons/yandex.svg', 'F10MPC5T', 'https://practicum.yandex.ru/', 'https://practicum.yandex.ru/'),
    ('TFNTGPA6', 'Stepik Premium', '/icons/stepik.svg', 'F10MPC5T', 'https://stepik.org/', 'https://stepik.org/'),
    ('CN8WBD52', 'Foxford', '/icons/foxford.svg', 'F10MPC5T', 'https://foxford.ru/', 'https://foxford.ru/'),
    ('X8H8QBF5', 'Duolingo Plus', '/icons/duolingo.svg', 'F10MPC5T', 'https://www.duolingo.com/', 'https://www.duolingo.com/super'),
    ('4QJGFZNC', 'Skyeng', '/icons/skyeng.svg', 'F10MPC5T', 'https://skyeng.ru/', 'https://skyeng.ru/'),
    ('A31F5JZZ', 'Альпина Digital', '/icons/alpinadigital.svg', 'F10MPC5T', 'https://alpinadigital.ru/', 'https://alpinadigital.ru/'),
    ('NT5HEXVB', 'Smart Reading', '/icons/smartreading.svg', 'F10MPC5T', 'https://smartreading.ru/', 'https://smartreading.ru/'),
    ('Q8R1NNQC', 'Постнаука Plus', '/icons/postnauka.svg', 'F10MPC5T', 'https://postnauka.org/', 'https://postnauka.org/'),
    ('88GJ3ESY', 'Arzamas Plus', '/icons/arzamas.svg', 'F10MPC5T', 'https://arzamas.academy/', 'https://arzamas.academy/'),
    ('A0GCX76F', 'Магистерия', '/icons/magisteria.svg', 'F10MPC5T', 'https://magisteria.ru/', 'https://magisteria.ru/'),
    ('C6GGRWQT', 'Strava Subscription', '/icons/strava.svg', 'E7ED6796', 'https://www.strava.com/', 'https://www.strava.com/subscribe'),
    ('14PQ26R9', 'Calm', '/icons/calm.svg', 'E7ED6796', 'https://www.calm.com/', 'https://www.calm.com/subscribe'),
    ('0FDDR4F0', 'Headspace', '/icons/headspace.svg', 'E7ED6796', 'https://www.headspace.com/', 'https://www.headspace.com/subscriptions'),
    ('4YEGZ5BT', 'Apple Fitness+', '/icons/apple.svg', 'E7ED6796', 'https://apps.apple.com/account/subscriptions', 'https://www.apple.com/apple-fitness-plus/'),
    ('S170QYXE', 'Peloton App', '/icons/peloton.svg', 'E7ED6796', 'https://www.onepeloton.com/', 'https://www.onepeloton.com/app'),
    ('C7ZWGTZP', 'Whoop', '/icons/whoop.svg', 'E7ED6796', 'https://www.whoop.com/', 'https://www.whoop.com/membership/'),
    ('09QMT0GR', 'Garmin Connect+', '/icons/garmin.svg', 'E7ED6796', 'https://www.garmin.com/', 'https://www.garmin.com/en-US/'),
    ('MC9VRKJC', 'Fitbit Premium', '/icons/fitbit.svg', 'E7ED6796', 'https://www.fitbit.com/', 'https://www.fitbit.com/global/us/products/services/premium'),
    ('P0R0A92B', 'Oura', '/icons/oura.svg', 'E7ED6796', 'https://ouraring.com/', 'https://ouraring.com/membership'),
    ('HQ3X7PDV', 'Future', '/icons/futureapp.svg', 'E7ED6796', 'https://future.co/', 'https://future.co/'),
    ('FXPV7DWR', 'Sleep Cycle Premium', '/icons/sleepcycle.svg', 'E7ED6796', 'https://www.sleepcycle.com/', 'https://www.sleepcycle.com/'),
    ('V8WA04HN', 'СберЗдоровье', '/icons/sberbank.svg', 'E7ED6796', 'https://sberhealth.ru/', 'https://sberhealth.ru/'),
    ('41HFGN63', 'Adobe Creative Cloud', '/icons/adobecreativecloud.svg', 'F6V8SZ0S', 'https://www.adobe.com/', 'https://www.adobe.com/creativecloud/plans.html'),
    ('WN5TZH74', 'Microsoft 365', '/icons/microsoft365.svg', 'F6V8SZ0S', 'https://account.microsoft.com/services', 'https://www.microsoft.com/microsoft-365'),
    ('78YTHTGT', 'Apple One', '/icons/apple.svg', 'F6V8SZ0S', 'https://apps.apple.com/account/subscriptions', 'https://www.apple.com/apple-one/'),
    ('XJBXPDRM', 'JetBrains All Products Pack', '/icons/jetbrains.svg', 'F6V8SZ0S', 'https://www.jetbrains.com/', 'https://www.jetbrains.com/store/'),
    ('W0DMD0YY', 'Figma Professional', '/icons/figma.svg', 'F6V8SZ0S', 'https://www.figma.com/', 'https://www.figma.com/pricing/'),
    ('MFJ9JZT2', 'Sketch', '/icons/sketch.svg', 'F6V8SZ0S', 'https://www.sketch.com/', 'https://www.sketch.com/pricing/'),
    ('440JPKBD', 'Webflow Workspace', '/icons/webflow.svg', 'F6V8SZ0S', 'https://webflow.com/', 'https://webflow.com/pricing'),
    ('0XJ03VXP', 'Framer Pro', '/icons/framer.svg', 'F6V8SZ0S', 'https://www.framer.com/', 'https://www.framer.com/pricing/'),
    ('E8F93P8F', 'Squarespace', '/icons/squarespace.svg', 'F6V8SZ0S', 'https://www.squarespace.com/', 'https://www.squarespace.com/pricing'),
    ('82YN1JHH', 'Wix Premium', '/icons/wix.svg', 'F6V8SZ0S', 'https://www.wix.com/', 'https://www.wix.com/upgrade/website'),
    ('G8D603SG', 'Cloudflare Pro', '/icons/cloudflare.svg', 'F6V8SZ0S', 'https://www.cloudflare.com/', 'https://www.cloudflare.com/plans/'),
    ('YA5XPPTZ', 'Vercel Pro', '/icons/vercel.svg', 'F6V8SZ0S', 'https://vercel.com/', 'https://vercel.com/pricing'),
    ('QAN30GD2', 'Netlify Pro', '/icons/netlify.svg', 'F6V8SZ0S', 'https://www.netlify.com/', 'https://www.netlify.com/pricing/'),
    ('PTMQG1MV', 'Heroku Eco', '/icons/heroku.svg', 'F6V8SZ0S', 'https://www.heroku.com/', 'https://www.heroku.com/pricing'),
    ('YV81W831', 'Railway Pro', '/icons/railway.svg', 'F6V8SZ0S', 'https://railway.com/', 'https://railway.com/pricing'),
    ('44E3DKS4', 'Render Pro', '/icons/render.svg', 'F6V8SZ0S', 'https://render.com/', 'https://render.com/pricing'),
    ('636KKX80', 'DigitalOcean', '/icons/digitalocean.svg', 'F6V8SZ0S', 'https://www.digitalocean.com/', 'https://www.digitalocean.com/pricing'),
    ('HD7HB3WX', 'GitHub', '/icons/github.svg', 'F6V8SZ0S', 'https://github.com/', 'https://github.com/pricing'),
    ('B1D01G2S', 'GitLab Premium', '/icons/gitlab.svg', 'F6V8SZ0S', 'https://about.gitlab.com/', 'https://about.gitlab.com/pricing/'),
    ('XXY4JAA7', 'Tower', '/icons/towergit.svg', 'F6V8SZ0S', 'https://www.git-tower.com/', 'https://www.git-tower.com/buy'),
    ('KTNQC9ZP', 'Setapp', '/icons/setapp.svg', 'F6V8SZ0S', 'https://setapp.com/', 'https://setapp.com/pricing'),
    ('E4FV6KG6', 'CleanMyMac X', '/icons/cleanmymac.svg', 'F6V8SZ0S', 'https://macpaw.com/', 'https://macpaw.com/cleanmymac'),
    ('WJXNCW0Z', 'Cinema 4D Subscription', '/icons/cinema4d.svg', 'F6V8SZ0S', 'https://www.maxon.net/', 'https://www.maxon.net/en/cinema-4d'),
    ('W4KTSKEG', 'Notion', '/icons/notion.svg', 'W6Y66ZRF', 'https://www.notion.so/', 'https://www.notion.so/pricing'),
    ('K0Z65X1M', 'Linear Standard', '/icons/linear.svg', 'W6Y66ZRF', 'https://linear.app/', 'https://linear.app/pricing'),
    ('Z60G2YJ9', 'Asana Premium', '/icons/asana.svg', 'W6Y66ZRF', 'https://asana.com/', 'https://asana.com/pricing'),
    ('7QX7NBCG', 'Trello Standard', '/icons/trello.svg', 'W6Y66ZRF', 'https://trello.com/', 'https://trello.com/pricing'),
    ('262KVWDP', 'ClickUp Unlimited', '/icons/clickup.svg', 'W6Y66ZRF', 'https://clickup.com/', 'https://clickup.com/pricing'),
    ('ZPEFA16A', 'Monday Basic', '/icons/mondaycom.svg', 'W6Y66ZRF', 'https://monday.com/', 'https://monday.com/pricing'),
    ('NRSJT95Q', 'Todoist Pro', '/icons/todoist.svg', 'W6Y66ZRF', 'https://todoist.com/', 'https://todoist.com/pricing'),
    ('Z9N4YD4X', 'TickTick Premium', '/icons/ticktick.svg', 'W6Y66ZRF', 'https://ticktick.com/', 'https://ticktick.com/'),
    ('2P21FE9M', 'Obsidian Sync', '/icons/obsidian.svg', 'W6Y66ZRF', 'https://obsidian.md/', 'https://obsidian.md/sync'),
    ('V8JRXCH1', 'Roam Research', '/icons/roamresearch.svg', 'W6Y66ZRF', 'https://roamresearch.com/', 'https://roamresearch.com/#/pricing'),
    ('P32HQAQN', 'Craft Standard', '/icons/craftapp.svg', 'W6Y66ZRF', 'https://www.craft.do/', 'https://www.craft.do/pricing'),
    ('EK1KC2FE', 'Evernote', '/icons/evernote.svg', 'W6Y66ZRF', 'https://evernote.com/', 'https://evernote.com/pricing'),
    ('YXT8M9N7', 'Slack Pro', '/icons/slack.svg', 'W6Y66ZRF', 'https://slack.com/', 'https://slack.com/pricing'),
    ('56M6CTRW', 'Zoom Pro', '/icons/zoom.svg', 'W6Y66ZRF', 'https://zoom.us/', 'https://zoom.us/pricing'),
    ('NABZ43N8', 'Loom Business', '/icons/loom.svg', 'W6Y66ZRF', 'https://www.loom.com/', 'https://www.loom.com/pricing'),
    ('SNTFB75N', 'Calendly Standard', '/icons/calendly.svg', 'W6Y66ZRF', 'https://calendly.com/', 'https://calendly.com/pricing'),
    ('RA44GB24', 'Akiflow Pro', '/icons/akiflow.svg', 'W6Y66ZRF', 'https://akiflow.com/', 'https://akiflow.com/pricing/'),
    ('WK6CZMP1', 'Motion', '/icons/motionapp.svg', 'W6Y66ZRF', 'https://www.usemotion.com/', 'https://www.usemotion.com/pricing'),
    ('BJVRJZXQ', 'Superhuman', '/icons/superhuman.svg', 'W6Y66ZRF', 'https://superhuman.com/', 'https://superhuman.com/pricing'),
    ('FPC41VCF', 'Hey', '/icons/heyemail.svg', 'W6Y66ZRF', 'https://www.hey.com/', 'https://www.hey.com/pricing/'),
    ('FPXHPG4K', 'Bitrix24', '/icons/bitrix24.svg', 'W6Y66ZRF', 'https://www.bitrix24.com/', 'https://www.bitrix24.com/prices/'),
    ('HS4MKYJ4', 'Yandex 360', '/icons/yandex.svg', 'W6Y66ZRF', 'https://360.yandex.ru/', 'https://360.yandex.ru/'),
    ('CP8JH105', 'Kaiten', '/icons/kaiten.svg', 'W6Y66ZRF', 'https://kaiten.ru/', 'https://kaiten.ru/'),
    ('5HSHSJAT', 'Reclaim.ai', '/icons/reclaimai.svg', 'W6Y66ZRF', 'https://reclaim.ai/', 'https://reclaim.ai/pricing'),
    ('VW0PDZAY', 'Xbox Game Pass', '/icons/xbox.svg', 'Y4PB344K', 'https://www.xbox.com/', 'https://www.xbox.com/xbox-game-pass'),
    ('G748HFXM', 'PlayStation Plus', '/icons/playstation.svg', 'Y4PB344K', 'https://www.playstation.com/', 'https://www.playstation.com/ps-plus/'),
    ('QFZ9GETM', 'Nintendo Switch Online', '/icons/nintendoswitch.svg', 'Y4PB344K', 'https://www.nintendo.com/', 'https://www.nintendo.com/switch/online-service/'),
    ('FFCSX3NE', 'EA Play', '/icons/ea.svg', 'Y4PB344K', 'https://www.ea.com/', 'https://www.ea.com/ea-play'),
    ('9X78SB6F', 'Ubisoft+', '/icons/ubisoft.svg', 'Y4PB344K', 'https://www.ubisoft.com/', 'https://www.ubisoft.com/'),
    ('SZ6WFNH4', 'Apple Arcade', '/icons/apple.svg', 'Y4PB344K', 'https://apps.apple.com/account/subscriptions', 'https://www.apple.com/apple-arcade/'),
    ('HXTY4FHX', 'GeForce NOW', '/icons/nvidia.svg', 'Y4PB344K', 'https://www.nvidia.com/', 'https://www.nvidia.com/en-us/geforce-now/'),
    ('Z6G2EZQG', 'Discord Nitro', '/icons/discord.svg', 'Y4PB344K', 'https://discord.com/', 'https://discord.com/nitro'),
    ('KJAGJ6X1', 'Roblox Premium', '/icons/roblox.svg', 'Y4PB344K', 'https://www.roblox.com/', 'https://www.roblox.com/'),
    ('CRXJH72N', 'World of Warcraft', '/icons/worldofwarcraft.svg', 'Y4PB344K', 'https://worldofwarcraft.blizzard.com/', 'https://worldofwarcraft.blizzard.com/en-us/start'),
    ('292H0BD9', 'Faceit Premium', '/icons/faceit.svg', 'Y4PB344K', 'https://www.faceit.com/', 'https://www.faceit.com/en/premium'),
    ('33NNQVGA', 'ESEA Premium', '/icons/esea.svg', 'Y4PB344K', 'https://play.esea.net/', 'https://play.esea.net/'),
    ('9P0H12CN', 'ChatGPT', '/icons/openai.svg', '5S0R9DSF', 'https://openai.com/', 'https://openai.com/chatgpt/pricing'),
    ('ZHH1B4Y9', 'Claude', '/icons/anthropic.svg', '5S0R9DSF', 'https://www.anthropic.com/', 'https://www.anthropic.com/pricing'),
    ('V315M6N2', 'Gemini Advanced', '/icons/gemini.svg', '5S0R9DSF', 'https://one.google.com/', 'https://one.google.com/about/google-ai-plans'),
    ('G690NKK3', 'Perplexity Pro', '/icons/perplexity.svg', '5S0R9DSF', 'https://www.perplexity.ai/', 'https://www.perplexity.ai/pro'),
    ('DRAXB38Y', 'Midjourney', '/icons/midjourney.svg', '5S0R9DSF', 'https://www.midjourney.com/', 'https://www.midjourney.com/explore'),
    ('985WFQ01', 'ElevenLabs Starter', '/icons/elevenlabs.svg', '5S0R9DSF', 'https://elevenlabs.io/', 'https://elevenlabs.io/pricing'),
    ('K6NMFRKA', 'GitHub Copilot', '/icons/githubcopilot.svg', '5S0R9DSF', 'https://github.com/', 'https://github.com/features/copilot/plans'),
    ('V8P9FC3P', 'Cursor Pro', '/icons/cursor.svg', '5S0R9DSF', 'https://www.cursor.com/', 'https://www.cursor.com/pricing'),
    ('5S5SJKMK', 'Replit Core', '/icons/replit.svg', '5S0R9DSF', 'https://replit.com/', 'https://replit.com/pricing'),
    ('7S7X9NE0', 'Suno Pro', '/icons/suno.svg', '5S0R9DSF', 'https://suno.com/', 'https://suno.com/pricing'),
    ('SSGKPFJW', 'Notion AI', '/icons/notion.svg', '5S0R9DSF', 'https://www.notion.so/', 'https://www.notion.so/product/ai'),
    ('S9DNEZ39', 'JetBrains AI Assistant', '/icons/jetbrains.svg', '5S0R9DSF', 'https://www.jetbrains.com/', 'https://www.jetbrains.com/ai/'),
    ('G4W9SQM4', 'Sourcegraph Cody Pro', '/icons/sourcegraph.svg', '5S0R9DSF', 'https://sourcegraph.com/', 'https://sourcegraph.com/pricing'),
    ('H820ZE6R', 'iCloud+', '/icons/icloud.svg', '5XVMJ5G6', 'https://apps.apple.com/account/subscriptions', 'https://www.apple.com/icloud/'),
    ('MBXK48J0', 'Google One', '/icons/googleone.svg', '5XVMJ5G6', 'https://myaccount.google.com/subscriptions', 'https://one.google.com/about'),
    ('JHYGWKG7', 'Dropbox', '/icons/dropbox.svg', '5XVMJ5G6', 'https://www.dropbox.com/', 'https://www.dropbox.com/plans'),
    ('TJCVHRE9', 'Microsoft OneDrive', '/icons/onedrive.svg', '5XVMJ5G6', 'https://account.microsoft.com/services', 'https://www.microsoft.com/microsoft-365/onedrive/online-cloud-storage'),
    ('JCAH85SS', 'Backblaze', '/icons/backblaze.svg', '5XVMJ5G6', 'https://www.backblaze.com/', 'https://www.backblaze.com/cloud-backup/personal'),
    ('DQXV93A5', 'Sync.com Pro', '/icons/synccom.svg', '5XVMJ5G6', 'https://www.sync.com/', 'https://www.sync.com/pricing/'),
    ('D8CN7BEK', 'Tresorit', '/icons/tresorit.svg', '5XVMJ5G6', 'https://tresorit.com/', 'https://tresorit.com/pricing'),
    ('XJ9Y0H2G', 'Proton Drive Plus', '/icons/protondrive.svg', '5XVMJ5G6', 'https://proton.me/', 'https://proton.me/drive/pricing'),
    ('ND6NHXAE', 'Mega Pro', '/icons/mega.svg', '5XVMJ5G6', 'https://mega.io/', 'https://mega.io/pricing'),
    ('GPR5P35T', 'Box Personal Pro', '/icons/box.svg', '5XVMJ5G6', 'https://www.box.com/', 'https://www.box.com/pricing/personal'),
    ('T5YA6CJZ', 'СберДиск', '/icons/sberbank.svg', '5XVMJ5G6', 'https://disk.sber.ru/', 'https://disk.sber.ru/'),
    ('1F10N8HJ', 'Telegram Premium', '/icons/telegram.svg', 'SSRFX6JE', 'https://telegram.org/', 'https://telegram.org/premium'),
    ('0JYWXAJ9', 'X Premium', '/icons/x.svg', 'SSRFX6JE', 'https://help.x.com/', 'https://help.x.com/en/using-x/x-premium'),
    ('ZYEW6F3Z', 'YouTube Premium', '/icons/youtube.svg', 'SSRFX6JE', 'https://myaccount.google.com/subscriptions', 'https://www.youtube.com/premium'),
    ('SEHN09F5', 'Reddit Premium', '/icons/reddit.svg', 'SSRFX6JE', 'https://www.reddit.com/', 'https://www.reddit.com/premium'),
    ('02VQ2ARA', 'Substack', '/icons/substack.svg', 'SSRFX6JE', 'https://substack.com/', 'https://substack.com/'),
    ('47NCCMTF', 'Twitch Subscription Tier 1', '/icons/twitch.svg', 'SSRFX6JE', 'https://www.twitch.tv/', 'https://www.twitch.tv/subs/all'),
    ('ZARN4KFS', 'NordVPN', '/icons/nordvpn.svg', 'SSRFX6JE', 'https://nordvpn.com/', 'https://nordvpn.com/order/'),
    ('KVZY443T', 'ExpressVPN', '/icons/expressvpn.svg', 'SSRFX6JE', 'https://www.expressvpn.com/', 'https://www.expressvpn.com/order'),
    ('QCJWHKJV', 'Surfshark', '/icons/surfshark.svg', 'SSRFX6JE', 'https://surfshark.com/', 'https://surfshark.com/pricing'),
    ('MQ6GV67A', 'ProtonVPN Plus', '/icons/protonvpn.svg', 'SSRFX6JE', 'https://protonvpn.com/', 'https://protonvpn.com/pricing'),
    ('P2ZXBDC4', 'Mullvad VPN', '/icons/mullvad.svg', 'SSRFX6JE', 'https://mullvad.net/', 'https://mullvad.net/en/account/create'),
    ('H244YSAG', 'CyberGhost', '/icons/cyberghost.svg', 'SSRFX6JE', 'https://www.cyberghostvpn.com/', 'https://www.cyberghostvpn.com/'),
    ('EAG3SV4H', 'Private Internet Access', '/icons/privateinternetaccess.svg', 'SSRFX6JE', 'https://www.privateinternetaccess.com/', 'https://www.privateinternetaccess.com/buy-vpn-online'),
    ('674Z3GDZ', '1Password', '/icons/1password.svg', 'SSRFX6JE', 'https://1password.com/', 'https://1password.com/sign-up'),
    ('NCYD7PMY', 'Bitwarden Premium', '/icons/bitwarden.svg', 'SSRFX6JE', 'https://bitwarden.com/', 'https://bitwarden.com/pricing/'),
    ('DEA4S4PD', 'Dashlane Premium', '/icons/dashlane.svg', 'SSRFX6JE', 'https://www.dashlane.com/', 'https://www.dashlane.com/pricing'),
    ('XKE57Q82', 'LastPass Premium', '/icons/lastpass.svg', 'SSRFX6JE', 'https://www.lastpass.com/', 'https://www.lastpass.com/pricing'),
    ('1ET9N4YN', 'Audible Premium Plus', '/icons/audible.svg', 'SSRFX6JE', 'https://www.audible.com/', 'https://www.audible.com/ep/membership'),
    ('TY6GBJY3', 'Букмейт', '/icons/bookmate.svg', 'SSRFX6JE', 'https://bookmate.com/', 'https://bookmate.com/about'),
    ('D1HK24RQ', 'Яндекс Плюс', '/icons/yandex.svg', 'SSRFX6JE', 'https://plus.yandex.ru/myplus', 'https://plus.yandex.ru/'),
    ('361K6J02', 'СберПрайм', '/icons/sberbank.svg', 'SSRFX6JE', 'https://prime.sber.ru/', 'https://prime.sber.ru/'),
    ('SBN21QQ6', 'Тинькофф Pro', '/icons/tinkoff.svg', 'SSRFX6JE', 'https://www.tinkoff.ru/', 'https://www.tinkoff.ru/pro/'),
    ('YXAE40HF', 'МТС Premium', '/icons/mts.svg', 'SSRFX6JE', 'https://premium.mts.ru/', 'https://premium.mts.ru/'),
    ('79CJHCB4', 'Grammarly Premium', '/icons/grammarly.svg', 'SSRFX6JE', 'https://www.grammarly.com/', 'https://www.grammarly.com/premium'),
    ('GKW939NY', 'Aura Identity Theft Protection', '/icons/aura.svg', 'SSRFX6JE', 'https://www.aura.com/', 'https://www.aura.com/'),
    ('FFNG4Z34', 'AdGuard Premium', '/icons/adguard.svg', 'SSRFX6JE', 'https://adguard.com/', 'https://adguard.com/license.html'),
    ('BYFMS6NG', 'Ozon Premium', '/icons/ozon.svg', 'SSRFX6JE', 'https://www.ozon.ru/', 'https://www.ozon.ru/premium/'),
    ('KW4WRD4Z', 'Lamoda Plus', '/icons/lamoda.svg', 'SSRFX6JE', 'https://www.lamoda.ru/', 'https://www.lamoda.ru/'),
    ('7HYXPXDA', 'Avito Pro', '/icons/avito.svg', 'SSRFX6JE', 'https://www.avito.ru/', 'https://www.avito.ru/pro'),
    ('J5SW0DFN', 'VK Combo', '/icons/vk.svg', 'SSRFX6JE', 'https://combo.vk.ru/', 'https://combo.vk.ru/'),
    ('M193NFYZ', 'Альфа Premium', '/icons/alfabank.svg', 'SSRFX6JE', 'https://alfabank.ru/', 'https://alfabank.ru/'),
    ('66W447XZ', 'ВТБ Привилегия', '/icons/vtb.svg', 'SSRFX6JE', 'https://www.vtb.ru/', 'https://www.vtb.ru/'),
    ('HPHWEC1X', 'Tele2 Mix', '/icons/tele2.svg', 'SSRFX6JE', 'https://tele2.ru/', 'https://tele2.ru/tariffs'),
    ('ZT61ZRBZ', 'Boosty', '/icons/boosty.svg', 'SSRFX6JE', 'https://boosty.to/', 'https://boosty.to/'),
    ('EEF050M0', 'Patreon', '/icons/patreon.svg', 'SSRFX6JE', 'https://www.patreon.com/', 'https://www.patreon.com/')
) AS v(sku, name, icon, category_sku, cancel_url, pricing_url)
JOIN "category" c ON c.sku = v.category_sku
ON CONFLICT ("sku") DO UPDATE SET
  "name"        = EXCLUDED."name",
  "icon"        = EXCLUDED."icon",
  "category_id" = EXCLUDED."category_id",
  "cancel_url"  = EXCLUDED."cancel_url",
  "pricing_url" = EXCLUDED."pricing_url";
